### ISSUE TITLE
Make Install not executing

### ISSUE THREAD

**Issue by TrixTec** [fabiodcorreia/catch-my-file#8]
In version 1.0, "sudo make install" ind installation directory is not functional, but works in version 0.1.0

OS: Linux Mint 20
![catch-my-file](https://user-images.githubusercontent.com/45968376/130203357-e80caf06-260c-4e4a-8a97-55e5d01113c8.png)

**Comment by fabiodcorreia** [comment]
@TrixTec are you using the linux package like CatchMyFile-1.0.0-linux-arm64.tar.gz?
From the screenshot looks like you are doing it from the source and that Makefile doesn't do the install, it's used to build and other development lifecycle tasks.
